name: 'Build Native Binaries'
description: 'Cross-compile native modules for multiple architectures'
inputs:
  os:
    description: 'Operating system for build'
    required: true
  arch:
    description: 'Architecture for build'
    required: true
  use-container:
    description: 'Use containerized build'
    required: false
    default: 'false'
  container-image:
    description: 'Container image for build'
    required: false
    default: 'build-image:latest'
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU for ARM64 cross-compilation
      if: inputs.arch == 'arm64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
        
    - name: Build native module (Direct)
      if: inputs.use-container == 'false'
      shell: bash
      run: |
        if [ "${{ inputs.arch }}" = "arm64" ]; then
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          export npm_config_arch=arm64
          export npm_config_target_arch=arm64
        fi
        # Set up pnpm environment for direct build
        corepack enable
        corepack use pnpm@latest
        pnpm run install:native
        
    - name: Build native module (Container)
      if: inputs.use-container == 'true'
      shell: bash
      run: |
        echo "🔨 Building native module for ${{ inputs.arch }} on ${{ inputs.os }}"
        
        # Create build container with appropriate architecture
        if [ "${{ inputs.arch }}" = "arm64" ]; then
          PLATFORM_FLAG="--platform linux/arm64"
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          export npm_config_arch=arm64
          export npm_config_target_arch=arm64
        else
          PLATFORM_FLAG="--platform linux/amd64"
        fi
        
        docker run --rm $PLATFORM_FLAG \
          -v $(pwd):/app \
          -w /app \
          --user root \
          --env NODE_ENV=production \
          --env CC=$CC \
          --env CXX=$CXX \
          --env npm_config_arch=$npm_config_arch \
          --env npm_config_target_arch=$npm_config_target_arch \
          --env TMPDIR=/app/tmp \
          --env HOME=/app \
          ${{ inputs.container-image }} \
          sh -c "
            # Create temp directory and set up environment
            mkdir -p /app/tmp &&
            # Configure npm for root user
            npm config set cache /app/tmp/.npm --global &&
            # Install and build as root (required in container)
            pnpm install --frozen-lockfile &&
            pnpm run install:native &&
            echo '✅ Native module compiled successfully'
          "
          
    - name: Package binary with prebuildify
      shell: bash
      run: |
        echo "📦 Packaging binary for ${{ inputs.arch }}"
        
        if [ "${{ inputs.arch }}" = "arm64" ]; then
          export npm_config_arch=arm64
          export npm_config_target_arch=arm64
        fi
        
        # Ensure the binary was built successfully
        if [ ! -d "build/Release" ]; then
          echo "❌ No build/Release directory found - build may have failed"
          exit 1
        fi
        
        # List available binaries for debugging
        echo "🔍 Available binaries:"
        find build/Release -name "*.node" -exec echo "  {}" \; || echo "  No .node files found"
        
        pnpm run build:native:prebuild
        echo "✅ Binary packaged successfully"
        
    - name: Validate packaged binary
      shell: bash
      run: |
        echo "🔍 Validating packaged binary for ${{ inputs.arch }}"
        
        # Check if prebuildify created binaries
        PREBUILT_BINARIES=$(find . -name "prebuilds" -type d)
        if [ -n "$PREBUILT_BINARIES" ]; then
          echo "✅ Found prebuildify directory: $PREBUILT_BINARIES"
          echo "📦 Prebuilt binaries:"
          find "$PREBUILT_BINARIES" -name "*.node" -exec echo "  {}" \; || echo "  No .node files found"
        else
          echo "❌ No prebuildify directory found"
          exit 1
        fi
        
    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ inputs.os }}-${{ inputs.arch }}
        path: |
          prebuilds/
          build/Release/
        retention-days: 30