name: 'Create Release'
description: 'Create GitHub release and upload binaries'
inputs:
  generate-notes:
    description: 'Generate release notes automatically'
    required: false
    default: 'true'
  draft:
    description: 'Create draft release'
    required: false
    default: 'false'
  prerelease:
    description: 'Create prerelease'
    required: false
    default: 'false'
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download all binary artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Prepare binaries for upload
      shell: bash
      run: |
        mkdir -p lib/binding/
        cp -r artifacts/*/lib/binding/* lib/binding/ || true
        
    - name: List prepared binaries
      shell: bash
      run: |
        echo "📦 Prepared binaries for release:"
        find lib/binding/ -name "*.tar.gz" -exec ls -la {} \; || echo "No binaries found"
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          lib/binding/*.tar.gz
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: ${{ inputs.generate-notes }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Upload binaries to GitHub Releases
      shell: bash
      run: |
        echo "🚀 Uploading binaries to release ${{ github.ref_name }}"
        
        # Find all binary files and upload them
        for file in lib/binding/*.tar.gz; do
          if [ -f "$file" ]; then
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file" --clobber
          fi
        done
        
        echo "✅ All binaries uploaded successfully"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}