name: 'Docker Build Setup'
description: 'Setup Docker Buildx, registry login, and metadata extraction'
inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Image name'
    required: false
    default: ${{ github.repository }}
  target:
    description: 'Docker build target'
    required: false
    default: 'runtime'
  push:
    description: 'Whether to push the image'
    required: false
    default: 'false'
  tags:
    description: 'Additional tags for the image'
    required: false
    default: ''
  cache-from:
    description: 'Cache source'
    required: false
    default: 'type=gha'
  cache-to:
    description: 'Cache destination'
    required: false
    default: 'type=gha,mode=max'
  platforms:
    description: 'Build platforms'
    required: false
    default: 'linux/amd64'
  file:
    description: 'Dockerfile path'
    required: false
    default: './Dockerfile.optimized'
  load:
    description: 'Load image to local daemon'
    required: false
    default: 'true'
  username:
    description: 'Registry username'
    required: false
    default: ${{ github.actor }}
  password:
    description: 'Registry password'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  login-enabled:
    description: 'Enable registry login'
    required: false
    default: 'true'
  is-pr:
    description: 'Running on pull request'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:buildx-stable-1
          
    - name: Cache Docker layers
      if: inputs.cache-from == 'type=local'
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    - name: Log in to Container Registry
      if: inputs.login-enabled == 'true' && inputs.is-pr == 'false'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          ${{ inputs.tags }}
          
    - name: Build and export container
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.file }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
        platforms: ${{ inputs.platforms }}
        
    - name: Output image name
      shell: bash
      run: |
        if [ "${{ inputs.push }}" = "true" ]; then
          echo "Built and pushed: ${{ steps.meta.outputs.tags }}"
        else
          echo "Built locally: ${{ steps.meta.outputs.tags }}"
        fi